// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Annotation = { id: string, label: string, description: string, };

export type Annotations = Array<Annotation>;
