// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IBindingsEpubBook, IBindingsEpubBookStructure } from "./epub";

export type Books = { EPUB: Array<IBindingsEpubBook>, };

export type IBookStructure = { EPUB?: IBindingsEpubBookStructure, };

export type IBookType = IBindingsEpubBook;
