// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IBindingsEpubBook, IBindingsEpubBookStructure } from './epub'
import type { IBindingsMobiBook, IBindingsMobiBookStructure } from './mobi'

export type Books = { EPUB: Array<IBindingsEpubBook>; MOBI: Array<IBindingsMobiBook> }

export type IBindingsBookContent = 'author' | 'description' | 'published' | 'publisher' | 'title'
export type IBookMetadata =
  | { format: 'EPUB'; metadata: { [key in IBindingsBookContent]?: string } }
  | { format: 'MOBI'; metadata: { [key in IBindingsBookContent]?: string } }

export type IBookStructure = IBindingsEpubBookStructure | IBindingsMobiBookStructure

export type IBookType = IBindingsEpubBook | IBindingsMobiBook
