// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";

export type IBindingsBookmark = { bookId: string, cfi: string, format: FormatType, updated_at: string, created_at: string, };
