// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";
import type { IBindingsMetadata } from "./metadata";
import type { ProgressType } from "./progress";
import type { IBindingsSection } from "./sections";
import type { IBindingsToc } from "./toc";

export type IBindingsBook = { metadata: IBindingsMetadata, createdAt: string, updatedAt: string, percentageProgress: string, progress: { [key in ProgressType]?: string }, format: FormatType, toc: IBindingsToc, sections: IBindingsSection, id: string, };

export type IBindingsBookContent = "author" | "description" | "published" | "publisher" | "title";

export type IBindingsBookStructure = { toc: IBindingsToc, sections: IBindingsSection, id: string, };

export type IBindingsRawBook = { createdAt: string, updatedAt: string, format: FormatType, id: string, };
