// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";

export type IBindingsBookmark = { bookId: string, cfi: string, chapter: string, title: string, format: FormatType, updatedAt: string, createdAt: string, };
