// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from './format'

export type IBindingsEpubBook = {
  metadata: IBindingsEpubMetadata
  rendition: IBindingsEpubRendition
  percentageProgress: string
  progress: Array<string>
  format: FormatType
  toc?: Array<IBindingsEpubToc>
  sections: Array<IBindingsEpubSection>
  id: string
}

export type IBindingsEpubBookStructure = {
  toc?: Array<IBindingsEpubToc>
  sections: Array<IBindingsEpubSection>
}

export type IBindingsEpubLayout = 'pre-paginated' | 'reflowable'

export type IBindingsEpubLocation = { current: number; next: number; total: number }

export type IBindingsEpubMetadata = {
  title: string
  author: string
  cover: string
  language: IEpubLanguage
  editor?: string
  publisher?: string
  contributor?: string
  modified?: string
  rights?: string
  published?: string
  description?: string
  subject?: string
  identifier?: string
  isbn?: string
  subtitle?: string
  series?: string
  seriesIndex?: number
  seriesTotal?: number
}

export type IBindingsEpubRendition = {
  layout?: IBindingsEpubLayout
  spread?: IBindingsEpubSpread
  viewport?: IBindingsEpubViewport
}

export type IBindingsEpubSection = {
  id: string
  cfi: string
  size: number
  linear?: string
  pageSpread?: IBindingsEpubSpread
}

export type IBindingsEpubSpread = 'left' | 'right' | 'center' | ''

export type IBindingsEpubToc = { label: string; href: string; subitems?: Array<IBindingsEpubToc> }

export type IBindingsEpubViewport = { width: number; height: number }

export type IEpubLanguage = string | Array<string>
