// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatType = "EPUB" | "PDF" | "MOBI" | "FB2" | "FBZ" | "ZIP" | "CBZ" | "AZW" | "AZW3";
