// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";

export type IBindingsMetadata = { id: string, format: FormatType, title: string, author: string, cover: string, language: ILanguage, publisher?: string, published?: string, contributor?: string, description?: string, identifier?: string, modified?: string, rights?: string, subject?: string, };

export type ILanguage = string | Array<string>;
