// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";
import type { ProgressType } from "./progress";

export type IBindingsMobiBook = { metadata: IBindingsMobiMetadata, percentageProgress: string, createdAt: string, updatedAt: string, progress: { [key in ProgressType]?: string }, format: FormatType, toc?: Array<IBindingsMobiToc>, sections: Array<IBindingsMobiSection>, id: string, };

export type IBindingsMobiBookStructure = { toc?: Array<IBindingsMobiToc>, sections: Array<IBindingsMobiSection>, format: FormatType, };

export type IBindingsMobiMetadata = { title: string, author: string, cover: string, language: IMobiLanguage, publisher?: string, published?: string, contributor?: string, description?: string, identifier?: string, modified?: string, rights?: string, subject?: string, };

export type IBindingsMobiSection = { id: number, size: number, };

export type IBindingsMobiToc = { label: string, href: string, subitems?: Array<IBindingsMobiToc>, };

export type IMobiLanguage = string | Array<string>;
