// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IBindingsNote = { value: string, bookId: string, note: string, page: string, noteId: string, chapter: string, title: string, text: string, createdAt: string, updatedAt: string, };
