// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatType } from "./format";

export type IBindingsPDFBook = { metadata: IBindingsPDFMetadata, percentageProgress: string, progress: { [key in string]?: string }, format: FormatType, toc?: Array<IBindingsPDFToc>, sections: Array<IBindingsPDFSection>, id: string, };

export type IBindingsPDFBookStructure = { sections: Array<IBindingsPDFSection>, toc?: Array<IBindingsPDFToc>, format: FormatType, };

export type IBindingsPDFMetadata = { title: string, author: string, cover: string, language?: string, publisher?: string, contributor?: string, published?: string, description?: string, identifier?: string, modified?: string, rights?: string, subject?: string, };

export type IBindingsPDFSection = { id: number, size: number, };

export type IBindingsPDFToc = { label: string, href: string, subitems?: Array<IBindingsPDFToc>, };
