// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IBindingsProgress = { id: string, percentageProgress: string, progress: { [key in ProgressType]?: string }, };

export type ProgressType = "CFI";
