// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IBindingsSection = { id: string, sections: Array<IBindingsSectionStruct>, };

export type IBindingsSectionStruct = { id: string, size: string, };
