// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IBindingsToc = { id: string, toc: Array<IBindingsTocStructure>, };

export type IBindingsTocStructure = { label: string, href: string, subitems: Array<IBindingsTocStructure>, };
