export enum SETTINGS {
  RESET_FONT_SETTINGS = 'RESET_FONT_SETTINGS',
  RESET_LAYOUT_SETTINGS = 'RESET_LAYOUT_SETTINGS',
  DEFAULT_FONT_SIZE = 'DEFAULT_FONT_SIZE',
  FONT_WEIGHT = 'FONT_WEIGHT',
  WORD_SPACING = 'WORD_SPACING',
  LETTER_SPACING = 'LETTER_SPACING',
  TEXT_INDENT = 'TEXT_INDENT',
  LINE_HEIGHT = 'LINE_HEIGHT',
}
