import { ThemeConfig } from 'antd'

export const theme: ThemeConfig = {
  token: {
    colorPrimary: '#58D39B',
    colorBgBase: '#222222',
    colorBgContainer: '#2A2A2A',
    colorBgElevated: '#181818',
    colorBorder: '#303030',
    borderRadius: 8,
    fontSize: 16,
    colorTextBase: '#FFFFFF',
    colorTextSecondary: '#C9C9C9',
    colorTextDisabled: '#6D6D6D',
  },
  components: {
    Drawer: {
      colorBgElevated: '#181818',
      colorBgMask: 'rgba(0, 0, 0, 0.65)',
      colorText: '#FFFFFF',
      colorIcon: '#C9C9C9',
      colorIconHover: '#FFFFFF',
    },
    Modal: {
      colorBgElevated: '#181818',
      colorText: '#FFFFFF',
      colorIcon: '#C9C9C9',
      colorIconHover: '#FFFFFF',
    },
    Segmented: {
      colorBgLayout: 'transparent',
      colorBgContainer: 'transparent',
      itemColor: '#C9C9C9',
      itemHoverColor: '#FFFFFF',
      itemSelectedColor: '#FFFFFF',
      itemHoverBg: '#242424',
      itemActiveBg: '#242424',
      itemSelectedBg: '#242424',
      colorIcon: '#C9C9C9',
      colorIconHover: '#FFFFFF',
    },
    Button: {
      colorBgContainer: '#2A2A2A',
      colorBgElevated: '#181818',
      colorPrimary: '#58D39B',
      colorText: '#FFFFFF',
    },
    Input: {
      colorBgContainer: '#2A2A2A',
      colorBorder: '#303030',
      colorText: '#FFFFFF',
      colorTextPlaceholder: '#9A9A9A',
    },
    Popover: {
      colorBgElevated: '#2D2D2D',
      colorBorder: '#424242',
      colorText: '#FFFFFF',
    },
    Slider: {
      colorPrimary: '#474747',
      colorPrimaryBorder: '#474747',
      colorPrimaryHover: '#9A9A9A',
      trackBg: '#474747',
      trackHoverBg: '#9A9A9A',
      handleColor: '#FFFFFF',
      handleActiveColor: '#FFFFFF',
      handleActiveOutlineColor: 'rgba(255, 255, 255, 0.2)',
      railBg: '#333333',
      railHoverBg: '#3F3F3F',
      dotActiveBorderColor: '#474747',
      colorText: '#FFFFFF',
    },
    Progress: {
      colorText: '#FFFFFF',
      colorBgContainer: '#333333',
      defaultColor: '#58D39B',
      colorSuccess: '#4CAF50',
      colorError: '#E54848',
      remainingColor: '#333333',
      lineBorderRadius: 8,
      circleTextColor: '#FFFFFF',
      colorTextLightSolid: '#FFFFFF',
      colorBgTextHover: '#2D2D2D',
      colorTextDescription: '#C9C9C9',
    },
    InputNumber: {
      colorBgContainer: '#2A2A2A',
      colorBorder: '#303030',
      colorText: '#FFFFFF',
      colorTextDescription: '#9A9A9A',
      colorPrimary: '#474747',
      colorPrimaryHover: '#474747',
      controlOutline: 'rgba(71, 71, 71, 0.1)',
      hoverBorderColor: '#474747',
      activeBorderColor: '#474747',
      handleBg: '#333333',
      handleActiveBg: '#202020',
      handleHoverColor: '#FFFFFF',
    },
  },
}
