export enum LOADER_STATE {
  IS_UPDATING_BOOKMARK_LABEL = 'IS_UPDATING_BOOKMARK_LABEL',
  IS_FETCHING_STRUCTURE = 'IS_FETCHING_STRUCTURE',
  IS_LOADING_STATE = 'IS_LOADING_STATE',
  IS_LOADING_ANNOTATIONS = 'IS_LOADING_ANNOTATIONS',
  IS_ADDING_BOOKMARK = 'IS_ADDING_BOOKMARK',
  IS_DELETING_BOOK = 'IS_DELETING_BOOK',
  IS_UPDATING_BOOK = 'IS_UPDATING_BOOK',
  IS_DELETING_BOOKMARK = 'IS_DELETING_BOOKMARK',
  IS_UPDATING_BOOKMARK = 'IS_UPDATING_BOOKMARK',
  IS_DELETING_NOTE = 'IS_DELETING_NOTE',
  IS_UPDATING_NOTE = 'IS_UPDATING_NOTE',
  IS_ADDING_BOOK = 'IS_ADDING_BOOK',
}

export enum LOADER_STATUS {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}
