export enum OPTIONS {
  OVERVIEW = 'OVERVIEW',
  CONTENTS = 'CONTENTS',
  ANNOTATIONS = 'ANNOTATIONS',
}

export enum ANNOTATION_OPTIONS {
  BOOKMARKS = 'BOOKMARKS',
  NOTES = 'NOTES',
  ALL = 'ALL',
}
